### ISSUE TITLE
Error when running generate_rba_model.py on example model

### ISSUE THREAD

**Issue by liebermeister** [SysBioInra/RBApy#10]
Hi all,

I am re-installing RBA. When I tried to run  generate_rba_model.py on the B subtilis model (from the github repo), I got the following error message. Can you help?

Thank you!
Best, Wolf

wolfram@persephone|/home/wolfram/projekte/rba/rba-framework/RBApy/github_COPY/Bacterial-RBA-models/Bacillus-subtilis-168-WT:python /home/wolfram/projekte/rba/rba-framework/RBApy/github_COPY/RBA-pipeline/generate_rba_model.py params.in
Importing SBML data...
Importing Uniprot data...
Traceback (most recent call last):
  File "/home/wolfram/projekte/rba/rba-framework/RBApy/github_COPY/RBA-pipeline/generate_rba_model.py", line 14, in <module>
    model = RbaModel.from_data(sys.argv[1])
  File "/home/wolfram/projekte/rba/rba-framework/RBApy/github_COPY/RBA-pipeline/rba/model.py", line 58, in from_data
    builder = rba.ModelBuilder(params_file)
  File "/home/wolfram/projekte/rba/rba-framework/RBApy/github_COPY/RBA-pipeline/rba/prerba/model_builder.py", line 24, in __init__
    self.data = UserData(parameter_file)
  File "/home/wolfram/projekte/rba/rba-framework/RBApy/github_COPY/RBA-pipeline/rba/prerba/user_data.py", line 31, in __init__
    self._import_uniprot_data()
  File "/home/wolfram/projekte/rba/rba-framework/RBApy/github_COPY/RBA-pipeline/rba/prerba/user_data.py", line 64, in _import_uniprot_data
    self.protein_data = ProteinData(self._input_dir())
  File "/home/wolfram/projekte/rba/rba-framework/RBApy/github_COPY/RBA-pipeline/rba/prerba/protein_data.py", line 44, in __init__
    self._uniprot = UniprotData(input_dir)
  File "/home/wolfram/projekte/rba/rba-framework/RBApy/github_COPY/RBA-pipeline/rba/prerba/uniprot_data.py", line 44, in __init__
    for entry, genes, annotation in zip(self.data.index, self.data['Gene names'], self.data['Annotation']):
  File "/usr/local/lib/python2.7/dist-packages/pandas/core/frame.py", line 2927, in __getitem__
    indexer = self.columns.get_loc(key)
  File "/usr/local/lib/python2.7/dist-packages/pandas/core/indexes/base.py", line 2659, in get_loc
    return self._engine.get_loc(self._maybe_cast_indexer(key))
  File "pandas/_libs/index.pyx", line 108, in pandas._libs.index.IndexEngine.get_loc
  File "pandas/_libs/index.pyx", line 132, in pandas._libs.index.IndexEngine.get_loc
  File "pandas/_libs/hashtable_class_helper.pxi", line 1601, in pandas._libs.hashtable.PyObjectHashTable.get_item
  File "pandas/_libs/hashtable_class_helper.pxi", line 1608, in pandas._libs.hashtable.PyObjectHashTable.get_item
KeyError: 'Annotation'

**Comment by m-jahn** [comment]
Hi Wolfram,
I was just working on my own RBA model and it is generated without error. When I try to generate the B. subtilis model I get the same error message as you. I think it is related to the fact that parsing and layout of the `uniprot.tsv` table have slightly changed over time. It worked when I deleted the original table and let RBApy download the newest table from uniprot by itself.

**Comment by AnneGoelzer** [comment]
Yes exactly. 
You need to delete the uniprot file and let RBApy upload the new version of uniprot file for your favorite organism.
Be careful that the new version of RBApy on the master branch integrates a new option in the file params.in, which helps to detect the location of transporters (i.e. the protein complex for which the activity is assigned to a michaelis menten by default)

**Comment by liebermeister** [comment]
Hi Michael and Anne,

thanks a lot!

Anne, don't you think in that case, we should delete the old uniprot file from the model directory? 

It doesn't make sense for users if running the pipeline (following the instructions) leads to a relatively cryptic error message. 
If you'd like to keep the old uniprot file in the directory (for legacy reasons, not for using it), I'd suggest to rename it (e.g. to uniprot-version_2018.csv) or to replace the uniprot.csv file by a subdirectory 'older-file-versions' and put the file into that subdirectory.

Thank you!

All the best,
Wolf

**Comment by AnneGoelzer** [comment]
done
