### ISSUE TITLE
Error when trying to install RBApy for python3

### ISSUE THREAD

**Issue by liebermeister** [SysBioInra/RBApy#11]
Hi all, 

I tried to install RBApy for the python3 version by using the command 

sudo python3 setup.py install

and get a weird error message. Can anyone help? Thank you!!

Best, Wolf

Traceback (most recent call last):
  File "setup.py", line 113, in <module>
    entry_points={
  File "/home/wolfram/.local/lib/python3.6/site-packages/setuptools/__init__.py", line 145, in setup
    return distutils.core.setup(**attrs)
  File "/usr/lib/python3.6/distutils/core.py", line 148, in setup
    dist.run_commands()
  File "/usr/lib/python3.6/distutils/dist.py", line 955, in run_commands
    self.run_command(cmd)
  File "/usr/lib/python3.6/distutils/dist.py", line 974, in run_command
    cmd_obj.run()
  File "/home/wolfram/.local/lib/python3.6/site-packages/setuptools/command/install.py", line 67, in run
    self.do_egg_install()
  File "/home/wolfram/.local/lib/python3.6/site-packages/setuptools/command/install.py", line 117, in do_egg_install
    cmd.run()
  File "/home/wolfram/.local/lib/python3.6/site-packages/setuptools/command/easy_install.py", line 418, in run
    self.easy_install(spec, not self.no_deps)
  File "/home/wolfram/.local/lib/python3.6/site-packages/setuptools/command/easy_install.py", line 660, in easy_install
    return self.install_item(None, spec, tmpdir, deps, True)
  File "/home/wolfram/.local/lib/python3.6/site-packages/setuptools/command/easy_install.py", line 707, in install_item
    self.process_distribution(spec, dist, deps)
  File "/home/wolfram/.local/lib/python3.6/site-packages/setuptools/command/easy_install.py", line 762, in process_distribution
    self.easy_install(dist.as_requirement())
  File "/home/wolfram/.local/lib/python3.6/site-packages/setuptools/command/easy_install.py", line 679, in easy_install
    return self.install_item(spec, dist.location, tmpdir, deps)
  File "/home/wolfram/.local/lib/python3.6/site-packages/setuptools/command/easy_install.py", line 710, in install_item
    self.process_distribution(spec, dists[0], deps, "Using")
  File "/home/wolfram/.local/lib/python3.6/site-packages/setuptools/command/easy_install.py", line 732, in process_distribution
    self.install_egg_scripts(dist)
  File "/home/wolfram/.local/lib/python3.6/site-packages/setuptools/command/easy_install.py", line 606, in install_egg_scripts
    dist.get_metadata('scripts/' + script_name)
  File "/home/wolfram/.local/lib/python3.6/site-packages/pkg_resources/__init__.py", line 1420, in get_metadata
    return value.decode('utf-8') if six.PY3 else value
UnicodeDecodeError: 'utf-8' codec can't decode byte 0xc0 in position 24: invalid start byte

**Comment by yexilein** [comment]
Hi Wolf,

I’m not able to reproduce your error (in a conda environment with python 3.6), so it is difficult to diagnose. The closest I have found by googling points to an error in pip itself. Could you try upgrading pip and confirm that the error persists ("pip3 install --upgrade pip3", maybe also "pip install --upgrade pip" just for safety)?

Stephan
